/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // books: [{ type: 'autogenerated', dirName: '.' }],
  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  dev: [
    'dev/index',
    {
      type: 'category',
      label: 'React',
      items: ['dev/react/nextjs-optimization/nextjs-optimization'],
    },
    {
      type: 'category',
      label: 'JS & TS',
      items: ['dev/jsts/introduction'],
    },
    {
      type: 'category',
      label: 'CS',
      items: [
        'dev/cs/stale-while-revalidate/stale-while-revalidate',
        'dev/cs/metrics/metrics',
        'dev/cs/lcp/lcp',
      ],
    },
    {
      type: 'category',
      label: 'Git',
      items: ['dev/git/sync-repository', 'dev/git/another-branch-push'],
    },
  ],
  books: [
    'books/introduction',
    {
      type: 'category',
      label: '클린코드',
      items: ['books/clean-code/introduction'],
    },
    {
      type: 'category',
      label: '프레임워크 없는 프론트엔드 개발',
      items: [
        'books/frameworkless-front-end-development/introduction',
        'books/frameworkless-front-end-development/01',
        'books/frameworkless-front-end-development/02',
        'books/frameworkless-front-end-development/03',
        'books/frameworkless-front-end-development/04',
        'books/frameworkless-front-end-development/05',
        'books/frameworkless-front-end-development/06',
      ],
    },
  ],
};

module.exports = sidebars;
